---
- name: get join command from master node
  hosts: controller
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw
  - name: set join command
    set_fact:
      join_command: "{{join_command_raw.stdout}}"


- name: join worker node to Cluster
  hosts: worker
  tasks:
  - name: join node
    shell: "{{hostvars['master-k8s'].join_command}}" 

