---
- name: install kubeadm kubectl kubelet
  hosts: k8s
  tasks:
  - name: Add Kubernetes Packages Repository
    yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck:  yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: kubelet kubeadm kubectl
  - name: install packages
    yum:
      name:
      - kubelet
      - kubeadm
      - kubectl
      disable_excludes: kubernetes
  - name: start and enable kubelet 
    service:
      name: kubelet
      state: started
      enabled: true
  - name: Reboot All Machines
    reboot:

