---
- name: install docker 
  hosts: k8s
  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
  - name: Install device-mapper-persistent-data
    yum:
      name: device-mapper-persistent-data
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
  - name: Install Docker
    yum:
      name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - name: make docker directory
    file:
      path: /etc/docker
      state: directory
  - name: configure docker daemon
    copy:
      src: daemon.json 
      dest: /etc/docker/daemon.json
  - name: start and enable docker service
    service:
      name: docker
      state: started
      enabled: true

